
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from io import BytesIO
from xml.sax.saxutils import escape as _escape
from typing import Any, Dict, List, Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors


def _money(v: Any, currency: str = "₹") -> str:
    try:
        return f"{currency}{float(v):,.0f}"
    except Exception:
        return f"{currency}0"


def _safe_str(x: Any) -> str:
    return "" if x is None else str(x)


def _kv_table(data: List[List[str]]) -> Table:
    tbl = Table(data, colWidths=[55*mm, 120*mm])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.whitesmoke),
        ("TEXTCOLOR", (0,0), (-1,0), colors.black),
        ("GRID", (0,0), (-1,-1), 0.25, colors.lightgrey),
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTNAME", (0,1), (-1,-1), "Helvetica"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("LEFTPADDING", (0,0), (-1,-1), 6),
        ("RIGHTPADDING", (0,0), (-1,-1), 6),
        ("TOPPADDING", (0,0), (-1,-1), 4),
        ("BOTTOMPADDING", (0,0), (-1,-1), 4),
    ]))
    return tbl


def generate_costing_pack_pdf(
    request_id: str,
    site_ref: str,
    inputs: Dict[str, Any],
    outputs: Dict[str, Any],
    generated_by: str = "",
    generated_at_iso: Optional[str] = None,
) -> bytes:
    """
    Creates an audit-ready PDF (Costing Pack) as bytes.
    Designed for internal Front Desk / Planning usage.
    """
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=16*mm,
        rightMargin=16*mm,
        topMargin=14*mm,
        bottomMargin=14*mm,
        title="FTTP Costing Pack",
        author=generated_by or "FTTP AI Command Center",
    )

    styles = getSampleStyleSheet()
    h1 = styles["Heading1"]
    h2 = styles["Heading2"]
    body = styles["BodyText"]
    body.fontSize = 10
    body.leading = 13

    story = []

    # Header
    story.append(Paragraph("FTTP Costing Pack", h1))
    story.append(Paragraph("Internal use only • Generated by Agentic Costing Workflow", body))
    story.append(Spacer(1, 6))

    gen_at = generated_at_iso or datetime.now().isoformat(timespec="seconds")
    meta_tbl = _kv_table([
        ["Field", "Value"],
        ["Request ID", _safe_str(request_id)],
        ["Site Ref", _safe_str(site_ref)],
        ["Generated at", _safe_str(gen_at)],
        ["Generated by", _safe_str(generated_by) or "—"],
        ["Status (system)", _safe_str(outputs.get("status") or "—")],
        ["Validation", _safe_str(outputs.get("validation") or "—")],
    ])
    story.append(meta_tbl)
    story.append(Spacer(1, 10))

    # Summary
    story.append(Paragraph("Summary", h2))
    final_cost = outputs.get("final_cost", outputs.get("total_cost", 0))
    build_method = outputs.get("build_method", "Hybrid")
    confidence = outputs.get("build_method_confidence", outputs.get("confidence_score", 0.5))
    survey = outputs.get("survey_required", False)

    summary_tbl = _kv_table([
        ["Metric", "Value"],
        ["Total estimate", _money(final_cost)],
        ["Build method", _safe_str(build_method)],
        ["Survey required", "Yes" if bool(survey) else "No"],
        ["Confidence", f"{float(confidence):.2f}" if confidence is not None else "—"],
    ])
    story.append(summary_tbl)
    story.append(Spacer(1, 10))

    # Inputs
    story.append(Paragraph("Request Inputs", h2))
    in_rows = [["Input", "Value"]]
    for k in ["site_ref", "distance", "premises", "build_type", "terrain", "traffic", "contractor", "priority", "requester"]:
        if k in inputs:
            in_rows.append([k, _safe_str(inputs.get(k))])
    story.append(_kv_table(in_rows))
    story.append(Spacer(1, 10))

    # Breakdown
    story.append(Paragraph("Cost Breakdown", h2))
    breakdown = outputs.get("cost_breakdown") or outputs.get("breakdown") or {}
    b_rows = [["Item", "Cost"]]
    if isinstance(breakdown, dict):
        for k, v in breakdown.items():
            b_rows.append([_safe_str(k), _money(v)])
    elif isinstance(breakdown, list):
        for row in breakdown[:100]:
            if isinstance(row, dict):
                item = row.get("item") or row.get("name") or "—"
                cost = row.get("cost") or row.get("value") or 0
                b_rows.append([_safe_str(item), _money(cost)])
    else:
        b_rows.append(["—", _money(0)])
    story.append(_kv_table(b_rows))
    story.append(Spacer(1, 10))

    # Risks / assumptions
    story.append(Paragraph("Risks & Assumptions", h2))
    top_risk = outputs.get("top_risk", "—")
    mitigation = outputs.get("risk_mitigation", outputs.get("mitigation", "—"))
    story.append(Paragraph(f"<b>Top risk:</b> {_safe_str(top_risk)}", body))
    story.append(Paragraph(f"<b>Mitigation:</b> {_safe_str(mitigation)}", body))
    story.append(Spacer(1, 6))

    assumptions = outputs.get("assumptions") or []
    if assumptions:
        story.append(Paragraph("<b>Assumptions:</b>", body))
        for a in assumptions[:12]:
            story.append(Paragraph(f"• {_safe_str(a)}", body))
    else:
        story.append(Paragraph("<b>Assumptions:</b> —", body))

    story.append(Spacer(1, 10))

    # Optimization
    opt = outputs.get("cost_optimization")
    if opt:
        story.append(Paragraph("AI Cost Optimization", h2))
        story.append(Paragraph(_safe_str(opt), body))
        story.append(Spacer(1, 6))

    doc.build(story)
    return buf.getvalue()


def generate_roi_report_pdf(
    *,
    title: str,
    observed: Dict[str, Any],
    inputs: Dict[str, Any],
    outputs: Dict[str, Any],
) -> bytes:
    """Generate a simple, audit-ready ROI report as a PDF."""
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=36, rightMargin=36, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet()
    h1 = styles["Heading1"]
    h2 = styles["Heading2"]
    body = styles["BodyText"]

    story = []
    story.append(Paragraph(_safe_str(title), h1))
    story.append(Paragraph("India FTTP costing • Internal", body))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Observed metrics", h2))
    obs_rows = [
        ["Period (days)", _safe_str(observed.get("period_days"))],
        ["Requests", _safe_str(observed.get("requests"))],
        ["Est. requests / month", _safe_str(observed.get("estimated_requests_per_month"))],
        ["Avg approved turnaround (hrs)", _safe_str(observed.get("avg_turnaround_hours_approved") or "—")],
        ["Avg final cost (₹)", _money(observed.get("avg_final_cost") or 0, currency="₹") if observed.get("avg_final_cost") else "—"],
    ]
    story.append(_kv_table(obs_rows))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Assumptions", h2))
    in_rows = [[k.replace("_", " ").title(), _safe_str(v)] for k, v in inputs.items()]
    story.append(_kv_table(in_rows[:16] if in_rows else [["—", "—"]]))
    story.append(Spacer(1, 10))

    story.append(Paragraph("ROI results", h2))
    out_rows = [
        ["Annual labour savings", _money(outputs.get("annual_labour_savings", 0), currency="₹")],
        ["Annual error avoidance", _money(outputs.get("annual_error_avoidance", 0), currency="₹")],
        ["Annual run cost", _money(outputs.get("annual_run_cost", 0), currency="₹")],
        ["Annual net benefit", _money(outputs.get("annual_net_benefit", 0), currency="₹")],
        ["Payback period (months)", _safe_str(outputs.get("payback_months") or "—")],
    ]
    story.append(_kv_table(out_rows))
    story.append(Spacer(1, 10))

    # Network Monetization Section
    nm = inputs.get("network_monetization")
    if nm:
        story.append(Paragraph("Network Monetization Analysis", h2))
        nm_rows = [
            ["Metric", "Value"],
            ["Linked Request", _safe_str(nm.get("linked_req_id") or "—")],
            ["Premises Passed", _safe_str(nm.get("premises_passed"))],
            ["Capex", _money(nm.get("capex", 0), currency="₹")],
            ["Take-up Rate", f"{nm.get('takeup_rate_pct')}%"],
            ["ARPU", _money(nm.get("arpu", 0), currency="₹") + "/mo"],
            ["Connected Users", _safe_str(nm.get("connected_users"))],
            ["Annual Revenue", _money(nm.get("annual_revenue", 0), currency="₹")],
            ["Annual EBITDA", _money(nm.get("annual_ebitda", 0), currency="₹")],
            ["Simple Payback", f"{nm.get('simple_payback_months', 0):.1f} months" if nm.get("simple_payback_months") else "—"],
        ]
        story.append(_kv_table(nm_rows))
        story.append(Spacer(1, 10))

    bullets = outputs.get("bullets") or []
    if bullets:
        story.append(Paragraph("Executive summary", h2))
        for b in bullets[:10]:
            story.append(Paragraph(f"• {_safe_str(b)}", body))

    doc.build(story)
    return buf.getvalue()


def generate_optimization_pack_pdf(
    request_id: str,
    site_ref: str,
    inputs: Dict[str, Any],
    outputs: Dict[str, Any],
    generated_by: str = "",
) -> bytes:
    """Dedicated optimization recommendations pack."""
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=24, rightMargin=24, topMargin=24, bottomMargin=24)

    styles = getSampleStyleSheet()
    title = styles["Title"]
    h2 = styles["Heading2"]
    body = styles["BodyText"]

    story = []
    story.append(Paragraph("FTTP Optimization Recommendations Pack", title))
    story.append(Paragraph(f"Request ID: {request_id} • Site: {site_ref}", body))
    if generated_by:
        story.append(Paragraph(f"Generated by: {generated_by}", body))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Context", h2))
    ctx_rows = [
        ["PIN / Site Ref", str(inputs.get("site_ref", site_ref))],
        ["Location", f"{inputs.get('latitude','')}, {inputs.get('longitude','')}".strip(", ")],
        ["Build method", str(outputs.get("build_method", "Hybrid"))],
        ["Terrain", str(inputs.get("terrain", ""))],
        ["Distance (m)", str(inputs.get("distance", ""))],
        ["Premises", str(inputs.get("premises", ""))],
    ]
    story.append(Table(ctx_rows, colWidths=[140, 360]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Recommendations", h2))
    opt = outputs.get("cost_optimization") or outputs.get("optimization") or "—"
    # Keep it readable
    story.append(Paragraph(_escape(str(opt)).replace("\n", "<br/>"), body))
    story.append(Spacer(1, 12))

    # Deterministic suggestions if present
    hints = outputs.get("optimization_suggestions") or []
    if isinstance(hints, list) and hints:
        story.append(Paragraph("Deterministic cost reduction options", h2))
        rows = [["Title", "Rationale", "Est. savings %"]]
        for h in hints[:8]:
            if isinstance(h, dict):
                rows.append([_escape(str(h.get("title",""))), _escape(str(h.get("rationale",""))), str(h.get("estimated_savings_pct",""))])
        story.append(Table(rows, repeatRows=1, colWidths=[130, 300, 70]))
        story.append(Spacer(1, 12))

    story.append(Paragraph("Notes", h2))
    story.append(Paragraph("Recommendations are guidance only. Final build decisions must follow field survey and governance approvals.", body))

    doc.build(story)
    return buf.getvalue()


def generate_monthly_summary_pdf(
    month_label: str,
    rows: List[Dict[str, Any]],
) -> bytes:
    """Monthly audit summary PDF."""
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=24, rightMargin=24, topMargin=24, bottomMargin=24)

    styles = getSampleStyleSheet()
    title = styles["Title"]
    h2 = styles["Heading2"]
    body = styles["BodyText"]

    story = []
    story.append(Paragraph("FTTP Audit Summary Report", title))
    story.append(Paragraph(f"Month: {month_label}", body))
    story.append(Spacer(1, 12))

    total = len(rows)
    by_status = {}
    for r in rows:
        stt = (r.get("status") or "DRAFT").upper()
        by_status[stt] = by_status.get(stt, 0) + 1

    story.append(Paragraph("Highlights", h2))
    story.append(Paragraph(f"Total requests: {total}", body))
    story.append(Paragraph("Status breakdown: " + ", ".join([f"{k}: {v}" for k,v in sorted(by_status.items())]), body))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Requests", h2))
    table_rows = [["Request ID", "PIN", "Status", "Final Cost"]]
    for r in rows[:120]:
        table_rows.append([
            _escape(str(r.get("request_id",""))),
            _escape(str(r.get("site_ref",""))),
            _escape(str(r.get("status",""))),
            _escape(str(r.get("final_cost",""))),
        ])
    story.append(Table(table_rows, repeatRows=1, colWidths=[150, 90, 110, 120]))

    doc.build(story)
    return buf.getvalue()
